name: Build

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.txt'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Cache maven
        id: maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/
          key: mvn-${{ hashFiles('.github/workflows/build.yml') }}
          restore-keys: mvn-

      - name: Set environments
        run: |
          {
            echo "version=v$(grep -oP 'versionName "\K[^"]+' app/build.gradle)"
            echo "commit=$(echo ${{ github.sha }} | cut -c-7)"
            echo "repo=$(echo ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/})"
          } >> $GITHUB_ENV

      - name: Checkout libxposed/api
        if: steps.maven.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: libxposed/api
          ref: 64e29bd657ef4d2540b34402f5a988778f29e676
          path: libxposed/api
          fetch-depth: 0

      - name: Build dependency
        if: steps.maven.outputs.cache-hit != 'true'
        working-directory: libxposed/api
        run: ./gradlew :api:publishApiPublicationToMavenLocal

      - name: Build module
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.repo }}(${{ env.version }}@${{ env.commit }})
          path: app/build/outputs/apk/debug/app-debug.apk
